window.TIMETABLE_DATA = {
  periods: [1, 2, 3, 4, 5, 6, 7],
  courses: {
    none: "なし",
    humanities: "文系",
    science: "理系",
    "explore-humanities": "探文",
    "explore-science": "探理",
    agriculture: "農",
    welfare: "福"
  },
  classes: [
    { id: "1-1-none", grade: "1", classNo: "1", course: "none", label: "11H" },
    { id: "1-2-none", grade: "1", classNo: "2", course: "none", label: "12H" },
    { id: "1-3-none", grade: "1", classNo: "3", course: "none", label: "13H" },
    { id: "1-4-none", grade: "1", classNo: "4", course: "none", label: "14H" },
    { id: "1-5-none", grade: "1", classNo: "5", course: "none", label: "15H" },
    { id: "1-6-none", grade: "1", classNo: "6", course: "none", label: "16H" },
    { id: "1-7-none", grade: "1", classNo: "7", course: "none", label: "17H" },
    { id: "2-1-explore-humanities", grade: "2", classNo: "1", course: "explore-humanities", label: "21H" },
    { id: "2-1-explore-science", grade: "2", classNo: "1", course: "explore-science", label: "21H" },
    { id: "2-2-science", grade: "2", classNo: "2", course: "science", label: "22H" },
    { id: "2-3-humanities", grade: "2", classNo: "3", course: "humanities", label: "23H" },
    { id: "2-4-humanities", grade: "2", classNo: "4", course: "humanities", label: "24H" },
    { id: "2-4-science", grade: "2", classNo: "4", course: "science", label: "24H" },
    { id: "2-5-humanities", grade: "2", classNo: "5", course: "humanities", label: "25H" },
    { id: "2-5-science", grade: "2", classNo: "5", course: "science", label: "25H" },
    { id: "2-6-agriculture", grade: "2", classNo: "6", course: "agriculture", label: "26H" },
    { id: "2-7-welfare", grade: "2", classNo: "7", course: "welfare", label: "27H" },
    { id: "3-1-humanities", grade: "3", classNo: "1", course: "humanities", label: "31H" },
    { id: "3-2-humanities", grade: "3", classNo: "2", course: "humanities", label: "32H" },
    { id: "3-2-science", grade: "3", classNo: "2", course: "science", label: "32H" },
    { id: "3-3-explore-humanities", grade: "3", classNo: "3", course: "explore-humanities", label: "33H" },
    { id: "3-3-explore-science", grade: "3", classNo: "3", course: "explore-science", label: "33H" },
    { id: "3-4-science", grade: "3", classNo: "4", course: "science", label: "34H" },
    { id: "3-5-humanities", grade: "3", classNo: "5", course: "humanities", label: "35H" },
    { id: "3-5-science", grade: "3", classNo: "5", course: "science", label: "35H" },
    { id: "3-6-none", grade: "3", classNo: "6", course: "none", label: "36H" },
    { id: "3-7-none", grade: "3", classNo: "7", course: "none", label: "37H" }
  ],
  baseTimetables: {
    "1-1-none": ["国語", "数学", "英語", "理科", "社会", "体育", ""],
    "1-2-none": ["数学", "英語", "国語", "社会", "理科", "音楽", ""],
    "1-3-none": ["英語", "国語", "数学", "理科", "社会", "体育", ""],
    "1-4-none": ["国語", "理科", "英語", "数学", "社会", "美術", ""],
    "1-5-none": ["社会", "数学", "理科", "英語", "国語", "体育", ""],
    "1-6-none": ["理科", "国語", "数学", "英語", "社会", "技術", ""],
    "1-7-none": ["英語", "数学", "社会", "国語", "理科", "家庭", ""],
    "2-1-explore-humanities": ["現文", "英表", "探究", "世界史", "古典", "体育", ""],
    "2-1-explore-science": ["数学", "物理", "探究", "英語", "化学", "体育", ""],
    "2-2-science": ["数学", "化学", "論表", "物理", "英語", "体育", ""],
    "2-3-humanities": ["現文", "世界史", "英語", "古典", "論表", "体育", ""],
    "2-4-humanities": ["現文", "世界史", "論表", "英語", "古典", "体育", ""],
    "2-4-science": ["数学", "化学", "論表", "物理", "英語", "体育", ""],
    "2-5-humanities": ["現文", "日本史", "英語", "論表", "古典", "体育", ""],
    "2-5-science": ["数学", "物理", "英語", "化学", "論表", "体育", ""],
    "2-6-agriculture": ["農業", "数学", "英語", "実習", "国語", "体育", ""],
    "2-7-welfare": ["福祉", "国語", "英語", "介護", "数学", "体育", ""],
    "3-1-humanities": ["現文", "古典", "英語", "日本史", "論表", "体育", ""],
    "3-2-humanities": ["古典", "世界史", "英語", "現文", "論表", "体育", ""],
    "3-2-science": ["数学", "物理", "化学", "英語", "論表", "体育", ""],
    "3-3-explore-humanities": ["探究", "古典", "現文", "英語", "日本史", "体育", ""],
    "3-3-explore-science": ["探究", "数学", "物理", "化学", "英語", "体育", ""],
    "3-4-science": ["数学", "化学", "物理", "論表", "英語", "体育", ""],
    "3-5-humanities": ["現文", "英語", "古典", "日本史", "論表", "体育", ""],
    "3-5-science": ["数学", "英語", "物理", "化学", "論表", "体育", ""],
    "3-6-none": ["国語", "数学", "英語", "選択", "体育", "総合", ""],
    "3-7-none": ["英語", "国語", "数学", "選択", "体育", "総合", ""]
  }
};
